spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: redis-container
    database: 0
    port: 6379
    password: