apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:

  restartPolicy: Never
  ## 定义一个vol 空的
  volumes:
    - name: shared-data
      emptyDir: {}

  containers:
    - name: nginx-container
      image: nginx:alpine
      volumeMounts:
        # shared-data => volumes 定义的vol
        - name: shared-data
          mountPath: /usr/share/nginx/html  #挂在目标

    # 只执行一次的容器，执行完毕后退出
    - name: debian-container
      image: debian:latest
      volumeMounts:
        - name: shared-data
          mountPath: /pod-data
      command: ["/bin/sh"]
      args: ["-c", "echo Hello from the debian container > /pod-data/index.html"]