apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    environment: development
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: xxx
  hostPath:
    path: /mnt/data
