apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-03
data:
  myvalue: "Hello World"
  drink: {{ .Values.favoriteDrink }}
  drink02: {{ .Values.favorite.drink }}
  food: {{ .Values.favorite.food }}